version: '2'
services:
  web:
    build: ../../containers/phplaravel
    ports:
      - "8080:80"
    volumes:
      - /home/febef/Init/ciinfra/proyects/sellingmachine/sellingmachine-site/:/app
    links:
      - mysql57
  mysql57:
    build: ../../containers/mysql
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOTPASSWORD=toor
    volumes:
      - /home/febef/Documentos/dockers/volumens/mysql57:/var/lib/mysql
