version: '2'
services:
  mysql57:
    build: ../../containers/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - ../volumes/mysql57:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql57
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql57
      PMA_USER: root
      PMA_PASSWORD: toor
    links:
      - mysql57

